version: 2
updates:
   - package-ecosystem: "npm"
     directory: "/"
     schedule:
        interval: "weekly"
        day: "saturday"
        time: "00:00"
        timezone: "America/Costa_Rica"
     open-pull-requests-limit: 30
     target-branch: "main"
     labels:
        - "dependencies"
     groups:
        dependencies:
           patterns:
              - "*"
